// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDscSp3LRvAFGCR7mshRmGjdnSQ7ced1ug',
    appId: '1:610148525403:web:1ac8934c77b3c9733c267e',
    messagingSenderId: '610148525403',
    projectId: 'sirusman-c5809',
    authDomain: 'sirusman-c5809.firebaseapp.com',
    storageBucket: 'sirusman-c5809.appspot.com',
    measurementId: 'G-DYBXD2NM3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7f8otsraVas7d4owyWd1APrq3mgvVnKI',
    appId: '1:610148525403:android:3b3d2d10eb3d79a93c267e',
    messagingSenderId: '610148525403',
    projectId: 'sirusman-c5809',
    storageBucket: 'sirusman-c5809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8JqqMzIODablDxmUyhqd73Ar7mULJ1b8',
    appId: '1:610148525403:ios:fcf2867eddc603383c267e',
    messagingSenderId: '610148525403',
    projectId: 'sirusman-c5809',
    storageBucket: 'sirusman-c5809.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8JqqMzIODablDxmUyhqd73Ar7mULJ1b8',
    appId: '1:610148525403:ios:d8e7b52985093a243c267e',
    messagingSenderId: '610148525403',
    projectId: 'sirusman-c5809',
    storageBucket: 'sirusman-c5809.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
